# Secret contenant le mot de passe PostgreSQL utilise par Odoo
apiVersion: v1
kind: Secret
metadata:
  name: odoo-db-secret
  namespace: icgroup
  labels:
    env: prod
type: Opaque
stringData:
  POSTGRES_USER: odoo
  POSTGRES_PASSWORD: odoo
  POSTGRES_DB: postgres
