# Secret contenant les identifiants de connexion a l'interface pgAdmin
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: icgroup
  labels:
    env: prod
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: admin@icgroup.com
  PGADMIN_DEFAULT_PASSWORD: admin
